export const BRANDS_PENDING = "BRANDS_PENDING";
export const BRANDS_SUCCESS = "BRANDS_SUCCESS";
export const BRANDS_FAILURE = "BRANDS_FAILURE";
export const BRANDS_UPDATE = "BRANDS_UPDATE";

export default [BRANDS_FAILURE, BRANDS_PENDING, BRANDS_SUCCESS, BRANDS_UPDATE];
