export const SPECIFIC_BRAND_PENDING = "SPECIFIC_BRAND_PENDING";
export const SPECIFIC_BRAND_FAILURE = "SPECIFIC_BRAND_FAILURE";
export const SPECIFIC_BRAND_SUCCESS = "SPECIFIC_BRAND_SUCCESS";
export const SPECIFIC_BRAND_UPDATE = "SPECIFIC_BRAND_UPDATE";

export default [
    SPECIFIC_BRAND_FAILURE,
    SPECIFIC_BRAND_PENDING,
    SPECIFIC_BRAND_SUCCESS,
    SPECIFIC_BRAND_UPDATE,
];
