export const allUsers = [
    {
        firstName: "Akin",
        lastName: "Abass",
        email: "mich@email.com",
        password: "password",
        role: "admin",
    },
    {
        firstName: "Ope",
        lastName: "Lukan",
        email: "ope@email.com",
        password: "password",
        role: "user",
    },
    {
        firstName: "Adebola",
        lastName: "Enitan",
        email: "yusuf@email.com",
        password: "password",
        role: "user",
    },
    {
        firstName: "Mose",
        lastName: "Ogunks",
        email: "mose@email.com",
        password: "password",
        role: "admin",
    },
    {
        firstName: "Mide",
        lastName: "Shopein",
        email: "tiolu@email.com",
        password: "password",
        role: "user",
    },
    {
        firstName: "Micky",
        lastName: "Kolade",
        email: "ko@email.com",
        password: "password",
        role: "user",
    },
    {
        firstName: "Chucks",
        lastName: "Okadigbo",
        email: "ok@email.com",
        password: "password",
        role: "user",
    },
];
